# @package _global_
dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 2048
  num_workers: 8  # or more, depending on your CPU cores
  prefetch_factor: 2
  pin_memory: true  # if using GPU (speeds up CPU→GPU transfer)
  persistent_workers: true  # avoids worker spawn overhead