# @package _global_
model:
  _target_: compactreasoningmodels.models.cnn.ConvNeuralNetwork
  hidden_channels: [32, 64, 128]
  kernel_size: 3
  dims: 2
  fc_hidden_size: 256
  fc_num_layers: 2
  pool_every: 2
  dropout: 0.1
