defaults:
  - data: nng5x5_parquet
  - model: recursive_gridmlp
  - optimizer: adam
  - criterion: abstain
  - split: random_split
  - logger: wandb
  - trainer: supervised
  - dataloader: default
  - scheduler: null
  - _self_

seed: 42
wandb_project: "nonograms_5x5_abstain"
