defaults:
  - data: nonogram_5x5_reward
  - model: simple_nn
  - optimizer: adam
  - criterion: nonogram
  - split: random_split
  - logger: wandb
  - trainer: reward
  - dataloader: default
  - scheduler: cosine_annealing
  - _self_

seed: 42
wandb_project: "nonograms_5x5"